apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: http-server
spec:
  secretName: http-server-tls
  dnsNames:
    - http-server.cathy.learning
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
