apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: http-server-image-secret
  namespace: kubernetes-learning
spec:
  vault:
    name: learning
    object:
      name: global-regcred
      type: secret
  output:
    secret:
      name: regcred
      type: kubernetes.io/dockerconfigjson
